version: '3.8'

services:
  web:
    image: antfoley14/django-translation-app:latest
    deploy:
      replicas: 1  # Number of instances to run
      # restart_policy:
      #   condition: on-failure
      restart_policy:
        condition: none
    secrets:
      - google_cloud_credentials  # Reference to the secret
      - source: google_cloud_credentials
        target: /booming-post-404017-49309d69296e.json  # Mount the secret to the container
    environment:
      GOOGLE_CLOUD_CREDENTIALS: /run/secrets/google_cloud_credentials  # Set the environment variable
    command: /bin/sh
    ports:
      - "8000:8000"  # Expose port 8000
    networks:
      - webnet

secrets:
  google_cloud_credentials:
    external: true  # Reference to an external Docker secret

networks:
  webnet:
