version: '3.8'

services:
  web:
    image: antfoley14/django-translation-app:latest
    deploy:
      replicas: 3  # Number of instances to run
      # restart_policy:
      #   condition: on-failure
    secrets:
      - google_cloud_credentials  # Reference to the secret
    environment:
      GOOGLE_CLOUD_CREDENTIALS: /run/secrets/google_cloud_credentials  # Set the environment variable
    ports:
      - "8000:8000"  # Expose port 8000
    networks:
      - webnet

secrets:
  google_cloud_credentials:
    external: true  # Reference to an external Docker secret

networks:
  webnet:
