# Generated by Django 5.1.1 on 2024-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginalLang', models.CharField(default='en', max_length=2)),
                ('desiredLang', models.CharField(max_length=2)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
