# Generated by Django 5.1.1 on 2024-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='orginalLang',
            new_name='originalLang',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='originalFile',
            field=models.FileField(default='blankFile', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='translatedFile',
            field=models.FileField(blank=True, null=True, upload_to='translated/'),
        ),
    ]
