# Generated by Django 4.2.16 on 2024-10-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_rename_orginallang_file_originallang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='apiVersion',
            field=models.CharField(default='v2', max_length=2),
        ),
    ]
