# Generated by Django 4.2.16 on 2024-10-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_file_apiversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='apiVersion',
            field=models.CharField(max_length=2),
        ),
    ]
