# Generated by Django 3.2.5 on 2024-10-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_alter_file_apiversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='translatedFile',
            new_name='translated_file',
        ),
    ]
