name: Django CI

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest] #add more OSs later if necessary
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Check Dependecies versions
      run: |
        python -m pip list
    - name: Set Up Google Transalte Credentials
      run: |
        echo "${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}" > "translation_app/booming-post-404017-49309d69296e.json"
    - name: Debug Google Cloud Credentials
      run: |
        echo "${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}"
    # - name: Check Credentials File Content
    #   run: |
    #     ls -d */
    #     cat "translation_app/booming-post-404017-49309d69296e.json"
    - name: Set Up Google Translate Credentials
      run: |
        cat <<EOF > "translation_app/booming-post-404017-49309d69296e.json"
        ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
        EOF
    - name: Check Credentials File Content
      run: |
        ls -d */
        cat "translation_app/booming-post-404017-49309d69296e.json"
    - name: Migrate to make sure no migrations needed
      env:
        GOOGLE_CLOUD_CREDENTIALS_PATH: "translation_app/booming-post-404017-49309d69296e.json"
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
