name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.6.0, 3.7.0, 3.8.0, 3.8.10, 3.9.1]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install --upgrade PyMuPDF
    - name: Migrate to make sure no migrations needed
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
    - name: Lint with Pylint
      run: |
        pip install pylint
        pylint Django_Translation_App
    - name: Run the Django development server
      run: |
        python manage.py runserver
        sleep 10
        curl http://127.0.0.1:8000/translation/upload/
